ALTER TYPE goal_status ADD VALUE IF NOT EXISTS 'proposed' AFTER 'draft';
ALTER TABLE goals ADD COLUMN IF NOT EXISTS scope TEXT;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS requires_approval BOOLEAN NOT NULL DEFAULT false;
