/**
 * Memory Bridge v2 — snapshot agent memories into a markdown primer
 * that Claude Code reads at the start of every session.
 *
 * The agent-server queries the DB, this module formats the result, and
 * a sibling route exposes it at GET /api/bridge/snapshot. A CLI script
 * consumes that endpoint and writes `.claude/agent-memories.md`.
 */

/** Minimal memory shape needed by the formatter — matches the db row. */
export interface BridgeMemory {
  id: string;
  category: string;
  key: string;
  content: string;
  importance: number;
  source: string | null;
  updatedAt: Date | string;
  archivedAt: Date | string | null;
}

export interface BridgeSnapshot {
  /** Absolute markdown ready to be written to .claude/agent-memories.md */
  markdown: string;
  /** Count of memories actually included (after filtering + limit) */
  includedCount: number;
  /** Count of memories that were archived or excluded */
  excludedCount: number;
  /** ISO timestamp the snapshot was generated */
  generatedAt: string;
}

export interface BuildSnapshotOptions {
  /** Max memories to include overall (default 40). */
  limit?: number;
  /** Max memories per category (default 8) to keep categories balanced. */
  perCategoryLimit?: number;
  /** Truncate each memory's content to this many chars (default 500). */
  maxContentChars?: number;
  /** Category ordering for the output (first = rendered first). */
  categoryOrder?: string[];
  /** "Now" override for deterministic tests. */
  now?: Date;
}

const DEFAULT_CATEGORY_ORDER = [
  "user_info",
  "preferences",
  "projects",
  "goals",
  "decisions",
  "technical",
  "business",
  "other",
];

const CATEGORY_LABELS: Record<string, string> = {
  user_info: "User Info",
  preferences: "Preferences",
  projects: "Projects",
  goals: "Goals",
  decisions: "Decisions",
  technical: "Technical",
  business: "Business",
  other: "Other",
};

function truncate(text: string, max: number): string {
  if (text.length <= max) return text;
  return text.slice(0, max - 1).trimEnd() + "…";
}

function formatMemory(m: BridgeMemory, maxContentChars: number): string {
  const content = truncate(m.content.replace(/\s+/g, " ").trim(), maxContentChars);
  const src = m.source ? ` _(${m.source})_` : "";
  return `- **${m.key}** — ${content} _(importance ${m.importance})_${src}`;
}

/**
 * Pure formatter: turn a list of memories into a markdown primer.
 * Filters archived, ranks by importance × recency, groups by category,
 * enforces per-category + global limits.
 */
export function buildMemorySnapshot(
  memories: BridgeMemory[],
  opts: BuildSnapshotOptions = {},
): BridgeSnapshot {
  const limit = opts.limit ?? 40;
  const perCategoryLimit = opts.perCategoryLimit ?? 8;
  const maxContentChars = opts.maxContentChars ?? 500;
  const categoryOrder = opts.categoryOrder ?? DEFAULT_CATEGORY_ORDER;
  const now = opts.now ?? new Date();

  let excluded = 0;

  // Filter archived
  const live = memories.filter((m) => {
    if (m.archivedAt) {
      excluded++;
      return false;
    }
    return true;
  });

  // Rank by importance first, then recency (updatedAt desc) as tiebreaker
  const ranked = [...live].sort((a, b) => {
    if (b.importance !== a.importance) return b.importance - a.importance;
    const aTime = new Date(a.updatedAt).getTime();
    const bTime = new Date(b.updatedAt).getTime();
    return bTime - aTime;
  });

  // Group by category with per-category cap
  const byCategory = new Map<string, BridgeMemory[]>();
  for (const m of ranked) {
    const bucket = byCategory.get(m.category) ?? [];
    if (bucket.length >= perCategoryLimit) {
      excluded++;
      continue;
    }
    bucket.push(m);
    byCategory.set(m.category, bucket);
  }

  // Enforce global limit — trim from the lowest-importance items across categories
  let included = 0;
  for (const bucket of byCategory.values()) included += bucket.length;
  if (included > limit) {
    // Flatten, re-rank, take top N, then regroup
    const flat = ranked.slice(0, limit);
    excluded += included - limit;
    byCategory.clear();
    for (const m of flat) {
      const bucket = byCategory.get(m.category) ?? [];
      bucket.push(m);
      byCategory.set(m.category, bucket);
    }
    included = limit;
  }

  // Render in deterministic category order; append any unknown categories at the end
  const seenCategories = new Set<string>();
  const lines: string[] = [];
  lines.push("# Jarvis Memory Snapshot");
  lines.push("");
  lines.push(
    `_Auto-generated by memory-bridge v2 at ${now.toISOString()}. ${included} memories, ${excluded} excluded (archived or trimmed)._`,
  );
  lines.push("");
  lines.push(
    "These are the highest-signal memories Jarvis has recorded. They describe the user, the project, decisions taken, and technical gotchas. Treat them the same way you treat CLAUDE.md — as durable context for this session.",
  );
  lines.push("");

  for (const category of categoryOrder) {
    const bucket = byCategory.get(category);
    if (!bucket || bucket.length === 0) continue;
    seenCategories.add(category);
    lines.push(`## ${CATEGORY_LABELS[category] ?? category}`);
    lines.push("");
    for (const m of bucket) {
      lines.push(formatMemory(m, maxContentChars));
    }
    lines.push("");
  }

  // Tail: any categories not in the ordering (forward-compat with new enum values)
  for (const [category, bucket] of byCategory.entries()) {
    if (seenCategories.has(category)) continue;
    if (!bucket.length) continue;
    lines.push(`## ${CATEGORY_LABELS[category] ?? category}`);
    lines.push("");
    for (const m of bucket) {
      lines.push(formatMemory(m, maxContentChars));
    }
    lines.push("");
  }

  if (included === 0) {
    lines.push(
      "_(No memories have been recorded yet. Save some via the `save_memory` MCP tool or `POST /api/memories`.)_",
    );
    lines.push("");
  }

  return {
    markdown: lines.join("\n"),
    includedCount: included,
    excludedCount: excluded,
    generatedAt: now.toISOString(),
  };
}
